# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1"

# SMTP email delivery for the notifications feature.
gem "mail", "~> 2.8"

group :development do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
end
