import * as core from "@actions/core";
import type { RunContext } from "./context.js";
import type { ProjectItem } from "../types.js";
import { estimateOf, isDone, iterationOf, requireField } from "../util/project.js";
import { postReport } from "./post.js";

/**
 * Sprint digest.
 *
 * Summarizes the most recently completed iteration: how many items were
 * completed vs carried over, and velocity (sum of estimates completed, when an
 * estimate field is configured). Posted as a comment or a new issue.
 */
export async function runDigest(ctx: RunContext): Promise<void> {
  const { cfg, graph } = ctx;
  const digest = cfg.features.digest;
  if (!digest) return;

  const iterationField = requireField(graph, cfg.fields.iteration, "digest");
  const completed = iterationField.completedIterations ?? [];
  if (completed.length === 0) {
    core.info("digest: no completed iteration to report on.");
    return;
  }
  const sprint = completed[0];

  const items = graph.items.filter((i) => iterationOf(i, cfg)?.iterationId === sprint.id);
  if (items.length === 0) {
    core.info(`digest: no items found in completed iteration "${sprint.title}".`);
    return;
  }

  const done = items.filter((i) => isDone(i, cfg));
  const carried = items.filter((i) => !isDone(i, cfg));
  const hasEstimate = Boolean(cfg.fields.estimate);
  const velocity = hasEstimate ? sum(done.map((i) => estimateOf(i, cfg) ?? 0)) : undefined;
  const committed = hasEstimate ? sum(items.map((i) => estimateOf(i, cfg) ?? 0)) : undefined;

  const body = [
    `## 🏁 Sprint digest — ${sprint.title}`,
    "",
    `- **Completed:** ${done.length} / ${items.length} items`,
    `- **Carried over:** ${carried.length} items`,
    ...(velocity !== undefined ? [`- **Velocity:** ${velocity}${committed !== undefined ? ` of ${committed} committed points` : ""}`] : []),
    "",
    ...(carried.length > 0 ? ["### Carried over", ...carried.map(listLine), ""] : []),
    ...(done.length > 0 ? ["### Completed", ...done.map(listLine), ""] : []),
    "_Generated by Boardly._",
  ].join("\n");

  await postReport(ctx, digest.postTo, "digest", `Sprint digest — ${sprint.title}`, body);
}

function listLine(item: ProjectItem): string {
  const c = item.content;
  if (!c) return "- _(draft item)_";
  return `- [#${c.number}](${c.url}) ${c.title}`;
}

function sum(nums: number[]): number {
  return nums.reduce((a, b) => a + b, 0);
}
