import * as core from "@actions/core";
import type { RunContext } from "./context.js";
import type { ProjectItem } from "../types.js";
import { statusOf, statusUpdatedAt } from "../util/project.js";
import { hoursBetween } from "../util/dates.js";
import { postReport } from "./post.js";

/**
 * Daily standup summary.
 *
 * Lists what moved in the look-back window (default 24h), grouped by assignee,
 * so a team can see at a glance what changed since yesterday.
 */
export async function runStandup(ctx: RunContext): Promise<void> {
  const { cfg, graph, now } = ctx;
  const standup = cfg.features.standup;
  if (!standup) return;

  const windowHours = standup.sinceHours;
  const moved = graph.items.filter((i) => {
    const changedAt = statusUpdatedAt(i, cfg) ?? i.content?.updatedAt ?? i.updatedAt;
    return hoursBetween(new Date(changedAt), now) <= windowHours;
  });

  if (moved.length === 0) {
    core.info(`standup: nothing moved in the last ${windowHours}h.`);
    return;
  }

  const byAssignee = new Map<string, ProjectItem[]>();
  for (const item of moved) {
    const assignees = item.content?.assignees.length ? item.content.assignees : ["_unassigned_"];
    for (const login of assignees) {
      const bucket = byAssignee.get(login) ?? [];
      bucket.push(item);
      byAssignee.set(login, bucket);
    }
  }

  const sections: string[] = [
    `## 🗓️ Standup — last ${windowHours}h`,
    "",
    `${moved.length} item(s) moved.`,
    "",
  ];
  for (const login of [...byAssignee.keys()].sort()) {
    const heading = login === "_unassigned_" ? "_Unassigned_" : `@${login}`;
    sections.push(`### ${heading}`);
    for (const item of byAssignee.get(login)!) {
      sections.push(lineFor(item, cfg));
    }
    sections.push("");
  }
  sections.push("_Generated by Boardly._");

  await postReport(ctx, standup.postTo, "standup", "Daily standup", sections.join("\n"));
}

function lineFor(item: ProjectItem, cfg: RunContext["cfg"]): string {
  const status = statusOf(item, cfg) ?? "No status";
  const c = item.content;
  if (!c) return `- _(draft item)_ — ${status}`;
  return `- [#${c.number}](${c.url}) ${c.title} — **${status}**`;
}
