# frozen_string_literal: true

require_relative "../util/project"
require_relative "post"

module Boardly
  module Features
    # Sprint digest: summarize the most recently completed iteration.
    module Digest
      module_function

      def run(ctx)
        cfg = ctx.cfg
        graph = ctx.graph
        digest = cfg.features[:digest]
        return unless digest

        field = Util::Project.require_field(graph, cfg.fields[:iteration], "digest")
        completed = field.completed_iterations || []
        if completed.empty?
          puts "digest: no completed iteration to report on."
          return
        end
        sprint = completed.first

        items = graph.items.select { |i| Util::Project.iteration_of(i, cfg)&.iteration_id == sprint.id }
        if items.empty?
          puts %(digest: no items found in completed iteration "#{sprint.title}".)
          return
        end

        done = items.select { |i| Util::Project.done?(i, cfg) }
        carried = items.reject { |i| Util::Project.done?(i, cfg) }
        has_estimate = !cfg.fields[:estimate].nil?
        velocity = has_estimate ? done.sum { |i| Util::Project.estimate_of(i, cfg) || 0 } : nil
        committed = has_estimate ? items.sum { |i| Util::Project.estimate_of(i, cfg) || 0 } : nil

        lines = ["## 🏁 Sprint digest — #{sprint.title}", ""]
        lines << "- **Completed:** #{done.length} / #{items.length} items"
        lines << "- **Carried over:** #{carried.length} items"
        lines << "- **Velocity:** #{velocity}#{committed ? " of #{committed} committed points" : ""}" unless velocity.nil?
        lines << ""
        unless carried.empty?
          lines << "### Carried over"
          carried.each { |i| lines << list_line(i) }
          lines << ""
        end
        unless done.empty?
          lines << "### Completed"
          done.each { |i| lines << list_line(i) }
          lines << ""
        end
        lines << "_Generated by Boardly._"

        Post.report(ctx, digest[:post_to], "digest", "Sprint digest — #{sprint.title}", lines.join("\n"))
      end

      def list_line(item)
        c = item.content
        return "- _(draft item)_" unless c

        "- [##{c.number}](#{c.url}) #{c.title}"
      end
    end
  end
end
