# frozen_string_literal: true

require_relative "../util/project"
require_relative "../util/dates"
require_relative "post"

module Boardly
  module Features
    # Daily standup: list what moved in the look-back window, grouped by assignee.
    module Standup
      module_function

      def run(ctx)
        cfg = ctx.cfg
        graph = ctx.graph
        standup = cfg.features[:standup]
        return unless standup

        window = standup[:since_hours]
        moved = graph.items.select do |i|
          changed = Util::Project.status_updated_at(i, cfg) || i.content&.updated_at || i.updated_at
          Util::Dates.hours_between(changed, ctx.now) <= window
        end

        if moved.empty?
          puts "standup: nothing moved in the last #{window}h."
          return
        end

        by_assignee = Hash.new { |h, k| h[k] = [] }
        moved.each do |item|
          assignees = item.content && !item.content.assignees.empty? ? item.content.assignees : ["_unassigned_"]
          assignees.each { |login| by_assignee[login] << item }
        end

        sections = ["## 🗓️ Standup — last #{window}h", "", "#{moved.length} item(s) moved.", ""]
        by_assignee.keys.sort.each do |login|
          heading = login == "_unassigned_" ? "_Unassigned_" : "@#{login}"
          sections << "### #{heading}"
          by_assignee[login].each { |item| sections << line_for(item, cfg) }
          sections << ""
        end
        sections << "_Generated by Boardly._"

        Post.report(ctx, standup[:post_to], "standup", "Daily standup", sections.join("\n"))
      end

      def line_for(item, cfg)
        status = Util::Project.status_of(item, cfg) || "No status"
        c = item.content
        return "- _(draft item)_ — #{status}" unless c

        "- [##{c.number}](#{c.url}) #{c.title} — **#{status}**"
      end
    end
  end
end
